### PR TITLE
Fix issues on simple params

### LINKED ISSUE #863: Non-compiling generated code when parameter is array type with enum validation and underscore in name
## Problem statement
If there is a query parameter that meets the following criteria:
1. The name has an underscore, e.g., some_parameter
2. The type is an array (of strings for the case I found)
3. The items of that array undergo enum validation

## Swagger specification
```
get:
   ...
   ...
   parameters:
     - name: some_parameter
        in: query
        ...
        type: array
        items:
          type: string
          enum:
            - enum1
            - enum2
            - enum3
```

The result of running swagger produces generated code that does not compile at the following sha: e4738db

In the generated code for getting the parameters, there's code like this:
```
someParameterI := someParameterIV

if err := validate.Enum(fmt.Sprintf("%s.%v", "some_parameter", i), "query", some_parameterI, []interface{}{"enum1", "enum2", "enum3"}); err != nil {
	return err
}
```

which obviously does not compile.

### LINKED ISSUE #909: UUIDs do not appear to be validated
## Problem statement

In a server: When attempting to validate a UUID in client-supplied data, the generated code under `restapi/operations` will make a call like

    value, err := formats.Parse("uuid", raw)

This will cause the `Parse()` function in `go-openapi/strfmt/format.go` to be called, which will attempt to validate the format of the client-supplied data by applying the `strfmt.UUID.UnmarshalText()` function. 

However, the `strfmt.UUID.UnmarshalText()` function (defined in `go-openapi/strfmt/default.go`) actually accepts any input string and not just those formatted as UUIDs. (There is a comment associated with that function: "validation is performed later on".)

Should validation of UUIDs should actually be performed using `strfmt.IsUUID()`?

## Environment

swagger version: 0.8.0 (commit: d1a0b6c1007402b2ccde73702eb0e8e43a5e7498)
go version: 1.7.4 linux/amd64 
OS: Fedora 25

### LINKED ISSUE #961: Validation for extended string format
## Problem statement

We can define that some property has extended string format ( for example ipv4). Then go-swagger generate this property with special type ( for ipv4 it is *strfmt.IPv4). But generated code don`t do validation for this type.
## Example:
swagger.yaml 
```
definitions:
  ethernet:
    type: object
    required:
      - ip
    properties:
      id:
        type: integer
        format: int32
        readOnly: true
      ip:
        type: string
        format: ipv4
```
We get file ethernet.go with code 
```
...
type Ethernet struct {
	// id
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// ip
	// Required: true
	IP *strfmt.IPv4 `json:"ip"`
}
...
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
	return nil
}
```
But why  it is not generated like this : 
```
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
// check that we get string in right format
	if err := validate.FormatOf("ip", "body", "ipv4", m.IP.String(), formats); err != nil {
		return err
	}
	return nil
}
```

## Environment
swagger version: 0.8.0

### LINKED ISSUE #1373: Generated server with form-data required=false evaluates file to nil
## Problem statement
When formData parameter is not required (required: false OR omitted), in the generated server io.ReadCloser always evaluates  to nil, even when file is supplied by the client.

When parameter is required it works fine

## Swagger specification
```yaml
paths:
  /jobs:
    post:
      operationId: JobCreator
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: yamlfile
          type: file
          description: Job description yaml file
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/JobID'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrResponse'
        '415':
          description: Unsupported media type (bad syntax)
          schema:
            $ref: '#/definitions/ErrResponse'
        '422':
          description: Invalid input (bad semantics)
          schema:
            $ref: '#/definitions/ErrResponse'
```
## Steps to reproduce
1. Generate server with a POST path and formData parameter that is NOT required
2. evaluate io.ReadCloser member of the parameters struct
3. make a request and check the io.ReadCloser member of the params struct
## Environment
swagger version: dev (pulled 10/JAN/2018 15:20 UTC)
go version: 1.9.2 
OS:   ubuntu 16.04

### LINKED ISSUE #1378: Default values for simple arrays generate code that does not compile
## Problem statement
When declaring default values for arrays, eg:
```yaml
default:
- a
- b
- c
```

the generated code for server does not produce a correct syntax.

Moreover, generated code attempts to parse the default value using the CollectionFormat, which is inconsistent with the model the value complies with.

## Swagger specification
@todo

## Environment
swagger version: [current master]
go version: 1.9.1
OS:   linux ubuntu

### LINKED ISSUE #1384: Generated configure file has confusing directions.
## Problem statement

Line 1 says "don't edit": https://github.com/go-swagger/go-swagger/blob/18337a2ecf1022fa5e6b3b01b3ac4033e1e4955b/generator/templates/server/configureapi.gotmpl#L1

But line 28 says "you should edit this file": https://github.com/go-swagger/go-swagger/blob/18337a2ecf1022fa5e6b3b01b3ac4033e1e4955b/generator/templates/server/configureapi.gotmpl#L28

These messages should be made consistent.

### PR DESCRIPTION
**Pull request by fredbi**
Fix issues on simple params: collections, nested collections and default values. Applied same rules for headers in responses.

_Supersedes PR #1372_

## Fixed issues
- fixes #909 
- fixes #961 (duplicate)
- fixes #1378 
- fixes #1384 
- fixes #863
- fixes #1373 

- fixed similar issues with nested arrays and default values in response headers
- this PR does **NOT** address known related issues with client generation
- however, urlbuilder now supports collections and nested collection for path params

## On the ci/testing side
- [x] Reviewed CircleCI config to split the original script in several more tractable and visible steps
- [x] Reviewed the run-canary.sh test vs valid/invalid specs. Added some "fixed" specs to move on further with generation testing ["fixed" means that spec validation issues where corrected to generate properly]
- [x] Introduced new code generation build test on ./fixtures/codegen + some other fixtures. The objective is to generate a server and build it

### CODE REVIEW

**Comment by fredbi** [comment]
Found a bug with duration type. Patching up.
For the longer term, I believe we would need a less hacky way of figuring out how to initialize custom types.

File: generator/template_repo.go [hunk 1]
```diff
@@ -207,6 +213,58 @@ func asPrettyJSON(data interface{}) (string, error) {
...
+	// NOTE: this is currently used to construct simple slice intializers for default values.
+	// This allows for nicer slice initializers for slices of primitive types and avoid systematic use for json.Unmarshal().
+	b, err := json.Marshal(data)
+	if err != nil {
+		return "", err
+	}
+	return strings.Replace(strings.Replace(strings.Replace(string(b), "}", ",}", -1), "[", "{", -1), "]", ",}", -1), nil
+}
+
+func hasDefaultParam(parameters GenParameters) bool {
```
Comment (casualjim) [inline generator/template_repo.go]: it seems odd that this has to be done at render time. Why isn't this just set on the parameter groups etc?

File: generator/template_repo.go [hunk 2]
```diff
@@ -207,6 +213,58 @@ func asPrettyJSON(data interface{}) (string, error) {
...
+	// NOTE: this is currently used by templates to avoid empty constructs
+	for _, param := range parameters {
+		if param.HasDefault {
+			return true
+		}
+	}
+	return false
+}
+
+func hasDefaultHeader(headers GenHeaders) bool {
```
Comment (casualjim) [inline generator/template_repo.go]: same remark as the paramters

File: generator/template_repo.go [hunk 3]
```diff
@@ -207,6 +213,58 @@ func asPrettyJSON(data interface{}) (string, error) {
...
+	// NOTE: this is currently used by templates to avoid empty constructs
+	for _, header := range headers {
+		if header.HasDefault {
+			return true
+		}
+	}
+	return false
+}
+
+func asItemsLocation(items interface{}) string {
```
Comment (casualjim) [inline generator/template_repo.go]: this is again not something that needs to be done in the templates but rather it's context so should go on the GenXxx models

File: generator/operation.go [hunk 4]
```diff
@@ -950,25 +977,37 @@ func (b *codeGenOpBuilder) MakeParameter(receiver string, resolver *typeResolver
 			Enum:             param.Enum,
 		}
 
+		res.ZeroValue = res.resolvedType.Zero()
+
 		if param.Items != nil {
+			if res.CollectionFormat == "" {
+				// When not defined,CollectionFormat defaults to csv
+				res.CollectionFormat = "csv"
```
Comment (casualjim) [inline generator/operation.go]: I'm not a fan of making it explicit like this because it risks the chance of breaking a default and sprinkles this handling all over the code. Whereas handling an empty value as default in the things that deal with strfmt seems wiser

File: generator/operation.go [hunk 5]
```diff
@@ -784,25 +796,34 @@ func (b *codeGenOpBuilder) MakeParameterItem(receiver, paramName, indexVar, path
 	res.Name = paramName
 	res.Path = path
 	res.Location = location
-	res.ValueExpression = swag.ToVarName(valueExpression)
+	res.ValueExpression = golang.MangleVarName(swag.ToGoName(valueExpression))
```
Comment (casualjim) [inline generator/operation.go]: why is there a need to change this?

File: generator/operation.go [hunk 6]
```diff
@@ -784,25 +796,34 @@ func (b *codeGenOpBuilder) MakeParameterItem(receiver, paramName, indexVar, path
...
 	res.CollectionFormat = items.CollectionFormat
+	if res.CollectionFormat == "" && items.Items != nil {
+		// When not defined,CollectionFormat defaults to csv
+		res.CollectionFormat = "csv"
```
Comment (casualjim) [inline generator/operation.go]: not a fan of this providing a value

File: generator/operation.go [hunk 7]
```diff
@@ -739,8 +743,12 @@ func (b *codeGenOpBuilder) MakeHeaderItem(receiver, paramName, indexVar, path, v
 	res.Name = paramName
 	res.Path = path
 	res.Location = "header"
-	res.ValueExpression = valueExpression
+	res.ValueExpression = golang.MangleVarName(swag.ToGoName(valueExpression))
```
Comment (casualjim) [inline generator/operation.go]: why does this need to change, it was working afaik

File: generator/operation.go [hunk 8]
```diff
@@ -739,8 +743,12 @@ func (b *codeGenOpBuilder) MakeHeaderItem(receiver, paramName, indexVar, path, v
...
 	res.CollectionFormat = items.CollectionFormat
+	if res.CollectionFormat == "" && items.Items != nil {
+		// When not defined,CollectionFormat defaults to csv
+		res.CollectionFormat = "csv"
```
Comment (casualjim) [inline generator/operation.go]: not a fan of this because it now sprinkles this across the codebase and people have to remember to do this. Better to postpone this until the last responsible moment

File: generator/operation.go [hunk 9]
```diff
@@ -709,6 +709,10 @@ func (b *codeGenOpBuilder) MakeHeader(receiver, name string, hdr spec.Header) (G
 	}
 
 	if hdr.Items != nil {
+		if res.CollectionFormat == "" {
+			// When not defined,CollectionFormat defaults to csv
+			res.CollectionFormat = "csv"
```
Comment (casualjim) [inline generator/operation.go]: not a fan of this because it now sprinkles this across the codebase and people have to remember to do this. Better to postpone this until the last responsible moment

File: generator/operation.go (hunk 7 above)
Comment (fredbi) [reply generator/operation.go]: got naming problems with headers when starting generating collections. I try to gather evidence for the change (please wait)

File: generator/operation.go (hunk 9 above)
Comment (fredbi) [reply generator/operation.go]: Need some guidance as I am not following you on this 
This was supposed to be done by spec (<= the first possible moment) and it is not.

Last possible moment is render time. Don't you think we haven't already loaded the templates enough with logics like this?

File: generator/template_repo.go (hunk 1 above)
Comment (fredbi) [reply generator/template_repo.go]: Was just easier to experiment with. I am replacing it with a struct member then.

File: generator/template_repo.go (hunk 3 above)
Comment (fredbi) [reply generator/template_repo.go]: ok. It jast just easier to avoid spreading too much changes everywhere. If now you agree with the change, I can make it to the Gen struct.

Another similar info not mentioned in your comments (because it's stealthier) is the choice of initialization method for default values (i.e. determining if a native initializer is used, a type conversion TYPE() construct, or calling to MarshalText())

This one should be a member of the GenXXX structs as well.

File: generator/operation.go (hunk 4 above)
Comment (fredbi) [reply generator/operation.go]: I understand, this means handling the default in templates, everywhere we use Split/JoinByFormat
Is it what you want? Even more logics in templates?

File: generator/operation.go (hunk 9 above)
Comment (casualjim) [reply generator/operation.go]: "" and "csv" should be functionally equivalent. The runtime, strfmt and swag functions that deal with this should equate "" and "csv".

File: generator/operation.go (hunk 4 above)
Comment (casualjim) [reply generator/operation.go]: no Splt and JoinByFormat already deal with the empty string case as csv

Comment (fredbi) [reply generator/operation.go]: OK. Will test this, though.

File: generator/template_repo.go (hunk 1 above)
Comment (fredbi) [reply generator/template_repo.go]: OK. Will do. Will add a HasSomeDefaults bool in the GenXXX structure for Params and Headers.
Will see later on if relevant to generalize this to models (there are some defaulting issues with models too... this story shall also be told)

File: generator/template_repo.go (hunk 2 above)
Comment (fredbi) [reply generator/template_repo.go]: OK

File: generator/template_repo.go (hunk 3 above)
Comment (fredbi) [reply generator/template_repo.go]: OK. 
BTW, this is just to generate a comment in source to more easily relate generated code to spec in nested loops. 
Do you think I should follow a specific guideline to allow some day the "generate spec" feature to benefit from this as well?

File: generator/formats.go [hunk 10]
```diff
@@ -117,6 +117,7 @@ var typeMapping = map[string]string{
 	// plus the following aliases:
 	//  - "datetime" alias for the more official "date-time"
 	//  - "objectid" and "ObjectId" aliases for "bsonobjectid"
+	// TODO: aliasing does not work, and was not really intended. Best to suppress it altogether.
```
[the remark this answers is not in the document]
Comment (fredbi) [reply generator/formats.go]: Format aliasing is more complex than it seemed at first and interacts with strfmt format normalizer.
Something is wrong somewhere, I don't know exactly where, but I didn't fix it yet. Hence the TODO. 
I feel that all the fuss started with the introduction of bson support, but I am not sure really.

I remove the TODO. Anyhow, I plan to ditch this whole structure and hand it over to strfmt someday (as a first step toward real custom formats, but before plugin support)

**Comment by casualjim** [comment]
yeah it's fine, it's not a critical optimization

File: generator/operation.go (hunk 7 above)
Comment (fredbi) [reply generator/operation.go]: good catch: I left an intermediate experiment here. This is actually equivalent to the simple: swag.ToVarName().
Why this transform? Actually the idea came from issue #863 
Example for header: x-isAnOptionalHeader
With nested arrays constructs, I have an expressionValue at some point like 'x-IsAnOptionalHeader3I'
VarNaming it gives the more correct xIsAnOptionalHeader3I.
What is most important is that names are consistent with childs.

File: generator/operation.go (hunk 5 above)
Comment (fredbi) [reply generator/operation.go]: good catch. The ToVarName() is sufficient and issue #863 fix with items remains valid.

File: generator/operation.go (hunk 9 above)
Comment (fredbi) [reply generator/operation.go]: OK

File: generator/operation.go (hunk 8 above)
Comment (fredbi) [reply generator/operation.go]: ok.

File: generator/template_repo.go (hunk 1 above)
Comment (fredbi) [reply generator/template_repo.go]: Ok tested on home-made unit test suite

File: generator/template_repo.go (hunk 3 above)
Comment (fredbi) [reply generator/template_repo.go]: Done everything here but a "clean" method to select the proper initializer for default values, which is still a shaky hack in templates. Postponed.

**Comment by casualjim** [comment]
can you rebase this so I can squash the commits?
