### PR TITLE
Fix go generate command when --name is absent

### LINKED ISSUE #1746: skipping -A/--name option in generate server generates corrupt code
## Steps to reproduce
```
swagger generate server -f ./swagger.yaml ./generated --exclude-main 
go generate ./...
...
expected argument for flag `-A, --name', but got option `--spec'
restapi/configure_example_swagger_server.go:16: running "swagger": exit status 1
```
This is due to corrupt `go generate` line in restapi/configure_example_swagger_server.go:
`//go:generate swagger generate server --target .. --name  --spec ../swagger.yaml --exclude-main`

## Environment
swagger version: 
dev 
```
commit 44342aefb3ce6216edd146bcf4e6ab63d5a15eca (HEAD -> master, origin/master, origin/HEAD)
Author: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
Date:   Sun Oct 7 14:18:32 2018 +0200

    Handle relative path when using Go modules
    
    Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>

```
go version: 
go version go1.11 linux/amd64

### PR DESCRIPTION
**Pull request by fredbi**
Fixes #1746 

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: generator/server_test.go [hunk 1]
```diff
@@ -410,3 +411,28 @@ func TestServer_Issue1648(t *testing.T) {
 		assert.NoError(t, err)
 	}
 }
+
+func TestServer_Issue1746(t *testing.T) {
+	log.SetOutput(ioutil.Discard)
+	targetdir, err := ioutil.TempDir(".", "swagger_server")
+	_ = os.Chdir(targetdir)
```
Comment (golangcibot) [inline generator/server_test.go]: G104: Errors unhandled.

File: generator/server_test.go [hunk 2]
```diff
@@ -410,3 +411,28 @@ func TestServer_Issue1648(t *testing.T) {
...
+	defer func() {
+		_ = os.Chdir("..")
```
Comment (golangcibot) [inline generator/server_test.go]: G104: Errors unhandled.

File: generator/server_test.go [hunk 3]
```diff
@@ -410,3 +411,28 @@ func TestServer_Issue1648(t *testing.T) {
...
+		log.SetOutput(os.Stdout)
+		_ = os.RemoveAll(targetdir)
```
Comment (golangcibot) [inline generator/server_test.go]: G104: Errors unhandled.

File: generator/server_test.go (hunk 1 above)
Comment (fredbi) [reply generator/server_test.go]: Same story again : https://github.com/golangci/golangci-lint/issues/234
