### PR TITLE
Fix x-go-type imports missing

### LINKED ISSUE #1703: Bug in external type import using x-go-type
## Problem statement

When using `x-go-type` in definition, go-swagger does not add external package to imports in `restapi/operations/<operation>_responses.go`, resulting in build error:

```
# test/restapi/operations
../../restapi/operations/get_users_responses.go:26:10: undefined: my_pkg
```
Generated source file:

```go
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
        // my_pkg "github.com/user/external_repo/my_pkg" <--- Missing code
)

// GetUsersOKCode is the HTTP code returned for type GetUsersOK
const GetUsersOKCode int = 200

/*GetUsersOK Users list

swagger:response getUsersOK
*/
type GetUsersOK struct {

	/*
	  In: Body
	*/
	Payload my_pkg.MyUsers `json:"body,omitempty"`
}

// NewGetUsersOK creates GetUsersOK with default headers values
func NewGetUsersOK() *GetUsersOK {

	return &GetUsersOK{}
}

// WithPayload adds the payload to the get users o k response
func (o *GetUsersOK) WithPayload(payload my_pkg.MyUsers) *GetUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users o k response
func (o *GetUsersOK) SetPayload(payload my_pkg.MyUsers) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(my_pkg.MyUsers, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
```

Somehow it works, when `alias` parameter in `x-go-type` is skipped, resulting in correctly added import (but without alias) and build success.

## Swagger specification
```yaml
swagger: '2.0'
info:
  title: x-go-type bug demo
  version: 1.0.0
paths:
  '/users':
    get:
      operationId: getUsers
      summary: List all users
      responses:
        '200':
          description: Users list
          schema:
            $ref: '#/definitions/Users'
definitions:
  Users:
    type: array
    items:
      type: string
    x-go-type:
      import:
        package: "github.com/user/external_repo/my_pkg"
        alias: "my_pkg"
      type: "MyUsers"
```
## Steps to reproduce

1. Save this swagger specification to file, for example `swagger.yml`
2. Run `swagger generate server -f swagger.yml`
3. Go to `restapi/operations/get_users_responses.go` and check imports section

## Environment
swagger version: 0.16.0
go version: 1.11
OS: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by moskal91**
This PR fixes missing imports when using `x-go-type` extension .

fixes #1703

### CODE REVIEW

**Comment by fredbi** [comment]
Thanks. Could you please add a unit test, e.g. with your sample spec causing the issue?

File: generator/operation_test.go [hunk 1]
```diff
@@ -557,6 +557,46 @@ func TestDateFormat_Spec2(t *testing.T) {
 	}
 }
 
+func TestBuilder_Issue1703(t *testing.T) {
+	log.SetOutput(ioutil.Discard)
+	defer log.SetOutput(os.Stdout)
+	dr, _ := os.Getwd()
```
Comment (golangcibot) [inline generator/operation_test.go]: G104: Errors unhandled.

**Comment by fredbi** [comment]
fixes #1703

**Comment by casualjim** [comment]
Can you sign this commit? https://help.github.com/articles/about-commit-signature-verification/

**Comment by moskal91** [comment]
Ok, commits squashed and signed with GPG key now.
