### PR TITLE
More mangling for generated package names and path

### LINKED ISSUE #1157: Generate client does not handle "-" dashes in --client-package consistently
## Problem statement
When generating client code from the swagger spec yaml and providing --client-package argument that contains dashes (`-`), generated code will be placed into the folder that has the same name that was given as --client-package but the `import` statements in the generated source code will refer to a folder name where all the dashes are replaced with underscores `_`.

## Swagger specification
2.0

## Steps to reproduce
1. Have a swagger spec file my_api_spec.yaml
2. Issue a command:
`/usr/bin/swagger generate client --client-package my-service --spec my_api_spec.yaml`

**Expected result:**
Client source code is generated under "**my-service**" folder and generated files contain import sections where the modules are referred to as `"<some path>/`**my-service**`/<module name>"`
**OR**
Client source code is generated under "**my_service**" folder and generated files contain import sections where the modules are referred to as `"<some path>/`**my_service**`/<module name>"`

**Actual result:**
Client source code is generated under the "**my-service**" folder BUT generated source code files contain import sections referring to the folder `"<some path>/`**my_service**`/<module name>"`

## Environment
swagger version:
docker image quay.io/goswagger/swagger:0.11.0
go version: 
go1.9 darwin/amd64
OS:   
linux alpine (https://quay.io/repository/goswagger/swagger?tag=0.11.0&tab=tags)

### LINKED ISSUE #1624: Can't have server code in subdirectory
## Problem statement

When passing -s argument as below which includes /, I was hoping that would allow the server code to be in a subdirectory:

`swagger generate server -f ./api/swagger/swagger.yaml -s pkg/srv`

However the import statements, for example in `configure_srv.go` are snake casing the package name:

`"github.com/xxx/app/pkg_srv/operations"`

## Swagger specification
2.0

## Environment
swagger version: 0.15.0
go version: 1.10.3
OS:  OS-X

### LINKED ISSUE #1683: Client wont compile with a route tagged "test"
## Problem statement

Have a swagger with a route tagged "test", it can generate the client but it wont compile.  The basic client file generated contains a struct referencing a package test_swagger which does not exist.

After a little digging it seems the template generation uses formatting function called snakize which changes the name (protection against reserved words) but not all formatting functions do this or use is inconsistent.

See here, this is the line that fails to compile for "test":

https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/facade.gotmpl#L120

This seems to boil down to a MangleFileName func which goes to a LanguageOpts fileNameFunc and there is a comment /code that does some special reserved word protection where it will append "_swagger" on to it

 - https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L83
 - https://github.com/go-swagger/go-swagger/blob/master/generator/shared.go#L168

So it seems this struct is having that package manipulated / matched the reserved word but other usages are not, neither is the import which is why the struct package is not found / failing to compile.

An example of a place using .Name directly.
https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/facade.gotmpl#L73

The other thing I noticed for the client operations it generates a folder in its name, which is "client/test" -- i.e. it doesn't attempt to do the _swagger.  So either snakize and some of the formatting functions are being a little over zealous or the _swagger notion is missing from a few places including the folder creations.  Thats when I entered a rabbit hole.

I also found this ticket:

https://github.com/go-swagger/go-swagger/issues/1157

Which also seems to have some inconsistency related to use of formatting functions.

The simple workaround is to tag the route as something a little more specific / not use a reserved word.

## Swagger specification

```
  /my/route/:
    get:
      operationId: getSomeData
      summary: Gets some data
      tags: [test]
```

## Steps to reproduce

Generate a client with a swagger file that contains a route tagged with "test", will generate but shouldnt compile.

## Environment
swagger version: 0.16.0  
go version: 1.10.3  
OS:   Linux Mint 18

### PR DESCRIPTION
**Pull request by fredbi**
Makes generation functional and consistent regarding:
* dashes in names
* reserved suffixes, which are meaningful for go, like 'test'
* sub-directories specified as target names (e.g. 'api/subdir')
* packages for client, model and server

* fixes #1683
* fixes #1157
* fixes #1624

* replaces #1790

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: generator/shared_test.go [hunk 1]
```diff
@@ -458,6 +458,44 @@ func TestShared_MangleFileName(t *testing.T) {
 	assert.True(t, strings.HasSuffix(res, "_test_swagger"))
 }
 
+func TestShared_ManglePackagePath(t *testing.T) {
```
Comment (golangcibot) [inline generator/shared_test.go]: 461-478 lines are duplicate of `generator/shared_test.go:480-497`

File: generator/shared_test.go [hunk 2]
```diff
@@ -458,6 +458,44 @@ func TestShared_MangleFileName(t *testing.T) {
...
+	assert.Equal(t, "x", res)
+
+	res = o.ManglePackagePath("a/b/c-d/e_f/g", "default")
+	assert.Equal(t, "a/b/c-d/e_f/g", res)
+
+	res = o.ManglePackagePath("a/b/c-d/e_f/g-h", "default")
+	assert.Equal(t, "a/b/c-d/e_f/g_h", res)
+}
+
+func TestShared_ManglePackageName(t *testing.T) {
```
Comment (golangcibot) [inline generator/shared_test.go]: 480-497 lines are duplicate of `generator/shared_test.go:461-478`

File: generator/client_test.go [hunk 3]
```diff
@@ -18,11 +18,102 @@ import (
...
 	"os"
+	"path/filepath"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
 )
 
+func testClientGenOpts() (g GenOpts) {
+	g.Target = "."
+	g.APIPackage = "operations"
```
Comment (golangcibot) [inline generator/client_test.go]: string `operations` has 2 occurrences, make it a constant

File: generator/client_test.go [hunk 4]
```diff
@@ -18,11 +18,102 @@ import (
...
+	g.ModelPackage = "models"
+	g.ServerPackage = "restapi"
+	g.ClientPackage = "client"
```
Comment (golangcibot) [inline generator/client_test.go]: string `client` has 2 occurrences, make it a constant

File: generator/client_test.go [hunk 5]
```diff
@@ -18,11 +18,102 @@ import (
...
+	err = GenerateClient("test", []string{"model1"}, []string{"op1", "op2"}, &opts)
+	assert.Error(t, err)
+
+	opts = testClientGenOpts()
+	opts.Spec = "dir/nowhere.yaml"
+	err = GenerateClient("test", []string{"model1"}, []string{"op1", "op2"}, &opts)
+	assert.Error(t, err)
+
+	opts = testClientGenOpts()
+	opts.Spec = "../fixtures/petstores/petstore.json"
```
Comment (golangcibot) [inline generator/client_test.go]: string `../fixtures/petstores/petstore.json` has 2 occurrences, make it a constant

File: generator/client_test.go [hunk 6]
```diff
@@ -18,11 +18,102 @@ import (
...
 	"testing"
 
 	"github.com/stretchr/testify/assert"
 )
 
+func testClientGenOpts() (g GenOpts) {
+	g.Target = "."
+	g.APIPackage = "operations"
+	g.ModelPackage = "models"
+	g.ServerPackage = "restapi"
```
Comment (golangcibot) [inline generator/client_test.go]: string `restapi` has 2 occurrences, make it a constant

File: generator/client_test.go [hunk 7]
```diff
@@ -18,11 +18,102 @@ import (
...
+	"path/filepath"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
 )
 
+func testClientGenOpts() (g GenOpts) {
+	g.Target = "."
+	g.APIPackage = "operations"
+	g.ModelPackage = "models"
```
Comment (golangcibot) [inline generator/client_test.go]: string `models` has 4 occurrences, make it a constant

**Comment by fredbi** [comment]
@MrLuje this is supposed to supersede your #1790 with more complete coverage. Feel free to check it out.
