### PR TITLE
Review of codegen imports and package name mangling 

### LINKED ISSUE #1049: Unable to override operations package name
## Problem statement
CLI client generator provides overrides for package names, but not for operations/operationGroups. The `{{ .Package }}` clauses in the `clientParameter` and `clientResponse` templates use the `tag` of the operation in the swaggerdoc instead. This makes the code generation a little difficult to use.

To give some background, my aim is to generate all client files at the top level in a single package.

## Environment
swagger version: dev
go version: 1.8.1
OS: Ubuntu 16.04

### LINKED ISSUE #1291: Has no field or method
after generating server from swagger.json:
`swagger generate server`

After installing dependencies:
`go get -v -u -f ./...`

Getting this kind of errors:
`restapi/configure_myproject_api_integration_documentation.go:39:42: api.GetAPIV1MymethodHandlerFunc undefined (type *operations.MyprojectAPIIntegrationDocumentationAPI has no field or method GetAPIV1MymethodHandlerFunc)`

### LINKED ISSUE #1971: Issue generating servers which have 'api' in their name
## Problem statement

There seems to be an issue when generating servers which have the text 'api' in their name. When generating a server with 'api' in the name the api part is stripped from the directory name in which the servers main.go is located. For example, running the generator with the following command

```
swagger generate server -f swagger.yaml --name custom-server-api
```

I would expect the main.go to be generated in the folder structure './cmd/custom-server-api-server/', however the main.go is actually generated in the folder './cmd/custom-server-server/'. 

I had a quick look through past issues and couldn't find anything reported similar to this issue. My apologies if this has been reported before.

## Swagger specification

Used example swagger spec defined [here](https://github.com/go-swagger/go-swagger/blob/master/examples/tutorials/custom-server/swagger/swagger.yml)

## Steps to reproduce

Run the command:

```
swagger generate server -f swagger.yaml --name custom-server-api
```

Notice that main.go is generated in the folder 'custom-server-server' instead of the expected folder 'custom-server-api-server'.

## Environment
swagger version: v0.19.0 
go version: go1.11.5 windows/amd64
OS: Windows

### LINKED ISSUE #2057: Swagger Tags interfere with imported packages
## Problem statement
Some tags in swagger specification may interfere with other imported packages. For example, if I specify tag `sync` then it interferes with Go `sync` package in import in `configure_....go` file. Current solution for me is not to use tag names that can interfere with other packages. But it would be better to fix this.

## Swagger specification
```
...
paths:
  /sync:
    post:
      operationId: SyncUser
      tags:
        - sync
...
```

## Environment
swagger version: 2.0 
go version: 1.12.7

### LINKED ISSUE #2111: Swagger tags starting with integer make formatting errors in operations
Hi guys, 

go-swagger has an issue to create operations from the swagger configuration if the path contains the first tag starting with an integer.

Sample swagger:
```
paths:
  /test:
    get:
      tags:
      - 123abc
      operationId: testId
      responses:
        200:
          description: Expected response to a valid request
          schema:
            type: object
```

Sample error:
```
$ package field 123abc
$ creating generated file "test_id_parameters.go" in "restapi\\operations\\123abc" as parameters
$ executed template asset:serverParameter
$ source formatting failed on template-generated source ("restapi\\operations\\123abc\\test_id_parameters.go" for parameters). Check that your template produces valid code 
$ unformatted generated source "test_id_parameters.go" has been dumped for template debugging purposes. DO NOT build on this source!
source formatting on generated source "parameters" failed: test_id_parameters.go:14:9: expected 'IDENT', found 123
```

I would like to keep this error here, as the output is not clear about the root cause.

## Temporary solution:
- rename tag to start with alphabet letter
- if multiple tags, use the first tag with alphabet letter

## Environment
swagger version: 0.21.0
go version: 1.13.4 
OS:  Windows

### PR DESCRIPTION
**Pull request by fredbi**
NOTE: Lean on previous preliminary refactoring work from PRs   #2177 and #2173 

* removed redundant code generation code regarding imports (and  let goimport sort it out)
* refactored imports in templates: imports are maps, codegen uses a language-specific funcmap

* mangle tag-based package names to safe names and use package aliasing

* introduced CLI option to disable tag-based package generation for operations
* introduced CLI option to override main server package location

* introduced x-go-operation-tag to alter tag-based package generation
* made global tag definition honor the x-go-name tag to alter tag-based package generation

* propagated changes to stratoscale contrib templates

Issues fixes:
* fixes #1049 (tag override)
* fixes #2111 (tag mangling)
* fixes #2057 (tag mangling)
* fixes #1291 (tag mangling)
* fixes #1971 (main package mangling & main target override)

TODO: name aliasing and mangling for imported models remains to be done

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: generator/language.go [hunk 1]
```diff
@@ -0,0 +1,432 @@
...
+// imports generate the code to import some external packages, possibly aliased
+func (l *LanguageOpts) imports(imports map[string]string) string {
+	if l.ImportsFunc != nil {
+		return l.ImportsFunc(imports)
+	}
+	return ""
+}
+
+// arrayInitializer builds a litteral array
+func (l *LanguageOpts) arrayInitializer(data interface{}) (string, error) {
```
Comment (golangcibot) [inline generator/language.go]: func `(*LanguageOpts).arrayInitializer` is unused (from `unused`)
