### PR TITLE
Fix failing tests

### LINKED ISSUE #3142: Allow disabling path uniqueness validation
## Problem statement

In an effort to have the go-swagger toolchain support the [resource name pattern described by Google's AIPs](https://cloud.google.com/apis/design/resource_names), I previously created this [PR](https://github.com/go-openapi/validate/pull/157) against the `go-openapi/validate` repo. I have been using a forking of this repo from 0.30.2 successfully since the PR was merged.

I was attempting to upstream it here but could not work through the errors. Link to patch: https://gist.github.com/dadgar/0ce4b7e49ffd34e9d74813a62f9f5f56

Applying the changes to v0.30.4 works but against `master` I get the following errors when generating the client:

```
$   swagger generate client -f swagger.json -t "$target" -A "cloud-iam" --allow-path-duplicates
...
2024/11/12 12:41:01 rendering 2 templates for operation cloud-iam
2024/11/12 12:41:01 name field AuthConfigService_CreateAuthConnection
2024/11/12 12:41:01 package field auth_config_service
2024/11/12 12:41:01 creating generated file "auth_config_service_create_auth_connection_parameters.go" in "../hcp-sdk-go/clients/cloud-iam/stable/2019-12-10/client/auth_config_service" as parameters
2024/11/12 12:41:01 executed template asset:clientParameter
2024/11/12 12:41:01 source formatting failed on template-generated source ("../hcp-sdk-go/clients/cloud-iam/stable/2019-12-10/client/auth_config_service/auth_config_service_create_auth_connection_parameters.go" for parameters). Check that your template produces valid code
2024/11/12 12:41:01 unformatted generated source "auth_config_service_create_auth_connection_parameters.go" has been dumped for template debugging purposes. DO NOT build on this source!
source formatting on generated source "parameters" failed: ../hcp-sdk-go/clients/cloud-iam/stable/2019-12-10/client/auth_config_service/auth_config_service_create_auth_connection_parameters.go:86:20: expected ';', found string (and 3 more errors)
```

Here is the generated file: https://gist.github.com/dadgar/67b169e31e6c7707eb78353cf49ca6ad

## Swagger specification
https://gist.github.com/dadgar/29750c3506fad3528fc1a33de8059267

## Steps to reproduce

On a non patched version, simply run the `swagger generate client` against the linked swagger specification.

## Environment
swagger version: 0.31.0  
go version go1.23.1 darwin/arm64

### PR DESCRIPTION
**Pull request by nikolaiianchuk**
Changes: 
- Fix broken links to OpenAPI-Specification
- revert #3122 

Unfortunately, have to revert #3122 due to the fact that it breaks tests. I guess on merging, due to the issue with tests running on a master branch instead of PR branch (see #3156) we didn't see that the PR tests were broken

Should be rebased after #3156 is merged to see that the tests pass, and only after that, we should merge this PR

Should fix #3142, as it is caused by changes in #3122

cc @casualjim

### CODE REVIEW

**Comment by nikolaiianchuk** [comment]
Seems like #3146 should actually fix #3122 changes that break the tests, so maybe instead of reverting would make more sense to merge it into this branch

File: generator/client_test.go [hunk 1]
```diff
@@ -172,7 +172,7 @@ func Test_GenerateClient(t *testing.T) {
 
 		t.Run("should dump template data", func(t *testing.T) {
 			opts := testClientGenOpts()
-			opts.Spec = "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml"
+			opts.Spec = "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/02e770ac80c137f8679f9d53fae52e470400d05d/examples/v2.0/yaml/petstore.yaml"
```
Comment (nikolaiianchuk) [inline generator/client_test.go:175]: this should also link to `old-v3.2.0-dev`

Comment (nikolaiianchuk) [reply generator/client_test.go]: Fixed

**Comment by casualjim** [comment]
I merged #3156

**Comment by nikolaiianchuk** [comment]
Thanks, rebasing

**Comment by nikolaiianchuk** [comment]
Let's see how the test jobs behave now

**Comment by nikolaiianchuk** [comment]
🤔

**Comment by nikolaiianchuk** [comment]
now lint fails for some reason 😫

**Comment by nikolaiianchuk** [comment]
I might have messed up the previous PR due to the fact I'm merging to another repo

cc @casualjim Sorry for bothering you for nothing, this is a bit unfortunate
I think I have another solution, but I guess we'll have to try and push it to master too, like the previous one.
Looking at example here: https://github.com/actions/checkout/issues/551

I'll create a new PR for CI

**Comment by nikolaiianchuk** [comment]
Created #3158 to hopefully finally fix it
A bit unfortunate, there's no proper way to test the CI

**Comment by casualjim** [comment]
yeah the only way I've found to do this with less friction is to run the actions in a fork

**Comment by nikolaiianchuk** [comment]
Thanks again, let's see how it goes

**Comment by nikolaiianchuk** [comment]
gonna rebase

**Comment by nikolaiianchuk** [comment]
Look at the linters and tests passing 🎉 

Something is up with the `build-doc` job, I'll take a look tomorrow.
Would be nice to fix the CI completely😀 

> WARN  Module "hugo-book" is not compatible with this Hugo version: Min 0.128.0; run "hugo mod graph" for more information.
> Start building sites … 
> Error: error building site: render: failed to render pages: render of "404" failed: "/home/runner/work/go-swagger/go-swagger/hack/doc-site/hugo/themes/hugo-book/layouts/404.html:5:7": execute of template failed: template: 404.html:5:7: executing "404.html" at <partial "docs/html-head" .>: error calling partial: "/home/runner/work/go-swagger/go-swagger/hack/doc-site/hugo/themes/hugo-book/layouts/partials/docs/html-head.html:26:87": execute of template failed: template: partials/docs/html-head.html:26:87: executing "partials/docs/html-head.html" at <css>: can't evaluate field Sass in type interface {}

Also, not sure what's going on with the `License Compliance` check

I'll also create and close a PR that should break some test/linter to double check that everything works as expected

Feel free to approve and merge this @casualjim

**Comment by nikolaiianchuk** [comment]
Tried to break things in PRs, works well enough. There's an issue with the linter annotations (they do not show up in `Files changed` tab for some reason), I'll look at that tomorrow
https://github.com/go-swagger/go-swagger/pull/3159
https://github.com/go-swagger/go-swagger/pull/3158

**Review by casualjim — APPROVED** [review]

File: generator/model.go [hunk 2]
```diff
@@ -2059,23 +2059,22 @@ func (sg *schemaGenContext) makeGenSchema() error {
 			sg.GenSchema.ExtraImports[alias] = pkg
 		}
 
-		if tpe.IsEmbedded {
-			sg.GenSchema.IsAnonymous = true
```
Comment (casualjim) [inline generator/model.go:2063]: doesn't this change the behavior

**Review by casualjim — CHANGES_REQUESTED** [review]

File: generator/model.go (hunk 2 above)
Comment (nikolaiianchuk) [reply generator/model.go:2063]: yes, it should revert #3122 as I found out that this was the change that broke the tests and introduced issue #3142

Comment (nikolaiianchuk) [reply generator/model.go:2063]: I think in this case it's easier to revert #3122 for now to make the master branch stable again, and then create a new PR for the #3122 feature (revert the revert) with the setup where the CI works well and triggers a failure on test errors and try to fix it in this new PR

Let me know what you think

**Comment by nikolaiianchuk** [comment]
Thank you!
