### PR TITLE
Go module aware scan

### LINKED ISSUE #1671: swagger generate spec throws a lot of errors with golang 1.11
## Problem statement

I install swagger from homebrew tap, then I run this command:

`swagger generate spec -o ./assets/swagger.json -m`

Now, I'm getting this error:

```
/usr/local/opt/go/libexec/src/internal/cpu/cpu_x86.go:9:7: CacheLineSize redeclared in this block
/usr/local/opt/go/libexec/src/internal/cpu/cpu_wasm.go:7:7: 	other declaration of CacheLineSize
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:14:6: Load redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:13:6: 	other declaration of Load
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:20:6: Loadp redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:19:6: 	other declaration of Loadp
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:26:6: Load64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:25:6: 	other declaration of Load64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:32:6: Xadd redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:30:6: 	other declaration of Xadd
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:40:6: Xadd64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:33:6: 	other declaration of Xadd64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:48:6: Xadduintptr redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:36:6: 	other declaration of Xadduintptr
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:56:6: Xchg redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:39:6: 	other declaration of Xchg
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:64:6: Xchg64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:42:6: 	other declaration of Xchg64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:72:6: Xchguintptr redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:45:6: 	other declaration of Xchguintptr
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:80:6: And8 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:48:6: 	other declaration of And8
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:86:6: Or8 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:51:6: 	other declaration of Or8
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:94:6: Cas64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:56:6: 	other declaration of Cas64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:104:6: Store redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:59:6: 	other declaration of Store
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:110:6: Store64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:62:6: 	other declaration of Store64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:116:6: StorepNoWB redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_amd64x.go:68:6: 	other declaration of StorepNoWB
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:12:6: Cas redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:122:6: 	other declaration of Cas
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:15:6: Casp1 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:132:6: 	other declaration of Casp1
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:18:6: Casuintptr redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:142:6: 	other declaration of Casuintptr
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:21:6: Storeuintptr redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:152:6: 	other declaration of Storeuintptr
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:24:6: Loaduintptr redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:158:6: 	other declaration of Loaduintptr
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:27:6: Loaduint redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:164:6: 	other declaration of Loaduint
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:32:6: Loadint64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:170:6: 	other declaration of Loadint64
/usr/local/opt/go/libexec/src/runtime/internal/atomic/stubs.go:35:6: Xaddint64 redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/atomic/atomic_wasm.go:176:6: 	other declaration of Xaddint64
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:8:2: ArchFamily redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:8:2: 	other declaration of ArchFamily
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:9:2: BigEndian redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:9:2: 	other declaration of BigEndian
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:10:2: CacheLineSize redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:10:2: 	other declaration of CacheLineSize
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:11:2: DefaultPhysPageSize redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:11:2: 	other declaration of DefaultPhysPageSize
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:12:2: PCQuantum redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:12:2: 	other declaration of PCQuantum
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:13:2: Int64Align redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:13:2: 	other declaration of Int64Align
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:14:2: HugePageSize redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:14:2: 	other declaration of HugePageSize
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:15:2: MinFrameSize redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:15:2: 	other declaration of MinFrameSize
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_wasm.go:18:6: Uintreg redeclared in this block
/usr/local/opt/go/libexec/src/runtime/internal/sys/arch_amd64.go:18:6: 	other declaration of Uintreg
/usr/local/opt/go/libexec/src/runtime/sys_x86.go:16:6: gostartcall redeclared in this block
/usr/local/opt/go/libexec/src/runtime/sys_wasm.go:31:6: 	other declaration of gostartcall
couldn't load packages due to errors: internal/cpu, runtime/internal/sys, runtime and 1 more
```

## Environment
swagger version: 0.16.0, commit: dd867fd63c30269ac217004c102f47a1774d4f5a
go version: 1.11
OS:  macos 10.13.6

### LINKED ISSUE #1681: Generate spec does not work with Go Modules
## Problem statement

the `swagger` CLI tool does not work correctly when the target repository is a Go 1.11 Module. The tool should not use `GOPATH/src` to resolve dependencies, and instead use the `GOPATH/pkg/mod` The possible failure cases I have discovered are as follows:

1. required dependency is not in GOPATH
    1. results in the CLI tool saying it cannot find dependency
1. dependency in GOPATH is not the same as declared in MODULE
    1. individual types/functions/packages fail, rather than the dependency as a whole

### LINKED ISSUE #1784: Swagger generate: can not import package
## Problem statement
My project (which is in $GOPATH) is using go modules. `go build ` works without any problem.
When I execute swagger generate I receive the error: 
capture

## Steps to reproduce
`swagger generate spec -o swagger.yml
`
## Environment
swagger version: dev
go version: 1.11.1
OS: linux Ubuntu

### LINKED ISSUE #1786: Installing with go get and go modules = on
## Problem statement

Having a problem installing swagger via go get when GO111MODULE is on.

## Steps to reproduce

$ export GO111MODULE=on
$ go get -u github.com/go-swagger/go-swagger/cmd/swagger
go: finding github.com/go-swagger/go-swagger/cmd/swagger latest
... etc
\# github.com/go-swagger/go-swagger/generator
/app/pkg/mod/github.com/go-swagger/go-swagger@v0.17.2/generator/template_repo.go:98:15: undefined: pretty.Sprint
/app/pkg/mod/github.com/go-swagger/go-swagger@v0.17.2/generator/types.go:658:50: undefined: pretty.Sprint

## Environment
go version: 1.11
OS:   linux

### LINKED ISSUE #1911: How to use swagger in go1.12 ?
I don't know how to use swagger in ```go1.12```. Could you give me a detailed example?
I always make mistakes when I execute.
```
api-demo $swagger generate spec -o ./swagger.json
/Users/zc/go/pkg/mod/github.com/jinzhu/gorm@v1.9.2/dialects/postgres/postgres.go:10:4: could not import github.com/lib/pq (cannot find package "github.com/lib/pq" in any of:
	/usr/local/opt/go/libexec/src/github.com/lib/pq (from $GOROOT)
	/Users/zc/go/src/github.com/lib/pq (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/jinzhu/gorm@v1.9.2/dialects/postgres/postgres.go:11:2: could not import github.com/lib/pq/hstore (cannot find package "github.com/lib/pq/hstore" in any of:
	/usr/local/opt/go/libexec/src/github.com/lib/pq/hstore (from $GOROOT)
	/Users/zc/go/src/github.com/lib/pq/hstore (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/jinzhu/gorm@v1.9.2/model_struct.go:12:2: could not import github.com/jinzhu/inflection (cannot find package "github.com/jinzhu/inflection" in any of:
	/usr/local/opt/go/libexec/src/github.com/jinzhu/inflection (from $GOROOT)
	/Users/zc/go/src/github.com/jinzhu/inflection (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:20:2: could not import github.com/gin-contrib/sse (cannot find package "github.com/gin-contrib/sse" in any of:
	/usr/local/opt/go/libexec/src/github.com/gin-contrib/sse (from $GOROOT)
	/Users/zc/go/src/github.com/gin-contrib/sse (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:21:2: could not import github.com/gin-gonic/gin/binding (cannot find package "github.com/gin-gonic/gin/binding" in any of:
	/usr/local/opt/go/libexec/src/github.com/gin-gonic/gin/binding (from $GOROOT)
	/Users/zc/go/src/github.com/gin-gonic/gin/binding (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:22:2: could not import github.com/gin-gonic/gin/render (cannot find package "github.com/gin-gonic/gin/render" in any of:
	/usr/local/opt/go/libexec/src/github.com/gin-gonic/gin/render (from $GOROOT)
	/Users/zc/go/src/github.com/gin-gonic/gin/render (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/errors.go:12:2: could not import github.com/gin-gonic/gin/json (cannot find package "github.com/gin-gonic/gin/json" in any of:
	/usr/local/opt/go/libexec/src/github.com/gin-gonic/gin/json (from $GOROOT)
	/Users/zc/go/src/github.com/gin-gonic/gin/json (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:14:2: could not import github.com/mattn/go-isatty (cannot find package "github.com/mattn/go-isatty" in any of:
	/usr/local/opt/go/libexec/src/github.com/mattn/go-isatty (from $GOROOT)
	/Users/zc/go/src/github.com/mattn/go-isatty (from $GOPATH))
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:62:37: undeclared name: isatty
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:62:67: undeclared name: isatty
/Users/zc/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:14:2: "github.com/mattn/go-isatty" imported but not used
couldn't load packages due to errors: github.com/gin-gonic/gin, github.com/jinzhu/gorm/dialects/postgres, github.com/jinzhu/gorm
```

### LINKED ISSUE #1970: There are always many error when my go version is 1.12.5 and not  in GOPATH.
## Problem statement
I can not generate a spec from source.There is always a problem.I think that is because my project not in GOPATH but I update my go to 1.12.5.And my project can run.I have gomod,and vendor.

## Steps to reproduce
image

## Environment
swagger version: dev
go version: 1.12.5
OS:   windows

### PR DESCRIPTION
**Pull request by casualjim**
Implements a scanner that is go module aware. 
It also loosens the restriction on requiring a main package. Now it accepts the same package syntax other go tools support eg. `./...` 

fixes #1970 
fixes #1911 
fixes #1786 
fixes #1784 
fixes #1681 
fixes #1671

contributes to #1724

### CODE REVIEW

File: codescan/parser.go [hunk 1]
```diff
@@ -0,0 +1,1467 @@
...
+	}
+	matches := rxDiscriminator.FindStringSubmatch(lines[0])
+	if len(matches) > 1 && len(matches[1]) > 0 {
+		req, err := strconv.ParseBool(matches[1])
+		if err != nil {
+			return err
+		}
+		if req {
+			su.schema.Discriminator = su.field
+		} else {
```
Comment (golangcibot) [inline codescan/parser.go]: elseif: can replace 'else {if cond {}}' with 'else if cond {}' (from `gocritic`)

File: codescan/parser.go [hunk 2]
```diff
@@ -0,0 +1,1467 @@
...
+			if includeTags[tag] {
+				return true
+			}
+		} else if len(excludeTags) > 0 {
+			if excludeTags[tag] {
+				return false
+			}
+		}
+	}
+	return len(includeTags) <= 0
```
Comment (golangcibot) [inline codescan/parser.go]: sloppyLen: len(includeTags) <= 0 can be len(includeTags) == 0 (from `gocritic`)

File: codescan/route_params.go [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+		case ParamTypeKey:
+			if current.Schema == nil {
+				current.Schema = new(spec.Schema)
+			}
+			if contains(basicTypes, value) {
+				current.Type = strings.ToLower(value)
+				if current.Type == TypeBool {
+					current.Type = TypeBoolean
+				}
+			} else {
```
Comment (golangcibot) [inline codescan/route_params.go]: elseif: can replace 'else {if cond {}}' with 'else if cond {}' (from `gocritic`)

File: codescan/parser.go [hunk 4]
```diff
@@ -0,0 +1,1467 @@
...
+		line := hdrs[0]
+		if rxPunctuationEnd.MatchString(line) {
+			title = []string{line}
+			desc = hdrs[1:]
+		} else {
+			desc = hdrs
+		}
+	}
+
+	return
```
Comment (golangcibot) [inline codescan/parser.go]: naked return in func `collectScannerTitleDescription` with 32 lines of code (from `nakedret`)

File: codescan/parser.go [hunk 5]
```diff
@@ -0,0 +1,1467 @@
...
+		return
+	}
+	err = u(data)
+	if err != nil {
+		return
+	}
+
+	// all parsed, returning...
+	sp.yamlSpec = nil // spec is now consumed, so let's erase the parsed lines
+	return
```
Comment (golangcibot) [inline codescan/parser.go]: naked return in func `UnmarshalSpec` with 43 lines of code (from `nakedret`)

File: codescan/parser.go [hunk 6]
```diff
@@ -0,0 +1,1467 @@
...
+					err = fmt.Errorf("invalid tag: %s", tag)
+				}
+				//return error
+				return
+			}
+		}
+	}
+
+	//TODO: Maybe do, if !parsedModelOrResponse {return some error}
+	return
```
Comment (golangcibot) [inline codescan/parser.go]: naked return in func `parseTags` with 70 lines of code (from `nakedret`)

File: codescan/application.go [hunk 7]
```diff
@@ -0,0 +1,576 @@
...
+	Include     []string
+	Exclude     []string
+	IncludeTags []string
+	ExcludeTags []string
+}
+
+type scanCtx struct {
+	pkgs    []*packages.Package
+	app     *typeIndex
+	builder *specBuilder
```
Comment (golangcibot) [inline codescan/application.go]: `builder` is unused (from `structcheck`)

File: codescan/parameters.go [hunk 8]
```diff
@@ -0,0 +1,454 @@
...
+		return nil
+	}
+	if pt.param.Schema == nil {
+		pt.param.Schema = new(spec.Schema)
+	}
+	return pt.param.Schema
+}
+
+func (pt paramTypable) AddExtension(key string, value interface{}) {
+	pt.AddExtension(key, value)
```
Comment (golangcibot) [inline codescan/parameters.go]: SA5007: infinite recursive call (from `staticcheck`)

File: generator/shared_test.go [hunk 9]
```diff
@@ -436,6 +436,10 @@ func TestShared_Issue1429(t *testing.T) {
 	log.SetOutput(ioutil.Discard)
 	defer log.SetOutput(os.Stdout)
 
+	if runtime.GOOS == "windows" {
+		t.Skip("on windows till the bug is resolved for ref resolution")
```
Comment (fredbi) [inline generator/shared_test.go]: ok this one is on my plate. I introduced a regression in go-openapi/analysis when running on windows.
