### PR TITLE
Models: avoids redundant "()" on .ValueExpression

### LINKED ISSUE #1839: Duplicated parentheses
## Problem statement

Generated code duplicates parentheses on method call. After generation I got errors like:

```go
if swag.IsZero(m.Attachments()()) { // not required
    return nil
}
```

m.Attachments()**()** <---- duplicated

## Swagger specification

[spec](https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/swagger.yaml)

## Steps to reproduce

```sh
swagger generate client \
    --additional-initialism=SMS \
    --additional-initialism=MMS \
    --additional-initialism=FAX \
    --name=clicksend \
    --spec=https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/swagger.yaml
```

## Environment
swagger version: 0.17.2 
go version: 1.11.3 
OS: MacOS Mojave

### PR DESCRIPTION
**Pull request by fredbi**
Models: avoids redundant "()" on .ValueExpression when using polymorphic type

* fixes #1839

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: generator/model.go [hunk 1]
```diff
@@ -258,7 +258,9 @@ func makeGenDefinitionHierarchy(name, pkg, container string, schema spec.Schema,
 		}
 
 		for j := range pg.GenSchema.Properties {
-			pg.GenSchema.Properties[j].ValueExpression += "()"
+			if !strings.HasSuffix(pg.GenSchema.Properties[j].ValueExpression, "()") {
+				pg.GenSchema.Properties[j].ValueExpression += "()"
```
Comment (golangcibot) [inline generator/model.go]: string `()` has 3 occurrences, make it a constant (from `goconst`)

File: generator/model.go [hunk 2]
```diff
@@ -32,6 +32,7 @@ import (
 	"github.com/go-openapi/swag"
 )
 
+const asMethod "()"
```
Comment (golangcibot) [inline generator/model.go]: missing constant value (from `typecheck`)
