### PR TITLE
Ordering security definitions and requirements

### LINKED ISSUE #1214: Security definition order is not consistent between code generations
## Problem statement

When we have multiple security definitions, the order they are generated in isn't consistent between runs.

## Swagger specification

`swagger: "2.0"
info:
  version: 0.0.0.0
  title: Test swagger spec for 1214
securityDefinitions:
  header:
    type: apiKey
    name: secret
    in: header
  query:
    type: apiKey
    name: secret
    in: query
security: ["header": [], "query": []]
paths:
  /foo:
    get:
      summary: "Add a new pet to the store"
      description: ""
      responses:
        200:
          description: "Success"`

## Steps to reproduce

Run swagger gen with above spec multiple times.

## Environment
swagger version: 0.12.0  
go version: 1.9.1  
OS: Linux

### PR DESCRIPTION
**Pull request by fredbi**
- fixes #1214 (stable codegen with security definitions)
- also sorts inner (joint) security requirements and associated scopes (although not currently used in templates)
- temporary work around for mishandling empty sec requirements in analysis (see https://github.com/go-openapi/analysis/pulls/29)

### CODE REVIEW

File: generator/operation.go [hunk 1]
```diff
@@ -1076,3 +1075,40 @@ func (b *codeGenOpBuilder) setBodyParamValidation(p *GenParameter) {
...
+// makeSecuritySchemes produces a sorted list of security requirements for this operation.
+// As for current, these requirements are not used by codegen (sec. requirement is determined at runtime).
+// We keep the order of the slice from the original spec, but sort the inner slice which comes from a map,
+// as well as the map of scopes.
+func (b *codeGenOpBuilder) makeSecurityRequirements(receiver string) []GenSecurityRequirements {
+	if b.Security == nil {
+		if b.Doc.Spec().Security == nil && b.Operation.Security == nil {
+			// work around bug in analysis.SecurityRequirementsFor()
+			// TODO: remove second check this when fixed in analysis
+			// nil (default requirement) is different than [] (no requirement)
```
Comment (casualjim) [inline generator/operation.go]: The changes in analysis were merged, you can remove this

File: generator/structs.go [hunk 2]
```diff
@@ -490,13 +489,13 @@ type GenApp struct {
...
-	SecurityDefinitions []GenSecurityScheme
+	SecurityDefinitions GenSecuritySchemes
 	Models              []GenDefinition
 	Operations          GenOperations
 	OperationGroups     GenOperationGroups
 	SwaggerJSON         string
-	// this is important for when the generated server adds routes
-	// ideally this should be removed after we code-generate the router instead of relying on runtime
+	// This is important for when the generated server adds routes.
+	// TODO: ideally this should be removed after we code-generate the router instead of relying on runtime
```
Comment (casualjim) [inline generator/structs.go]: There is a very distinct advantage to having that in runtime instead of as generated code.  So I don't think we should ever code generate the router.
If embedding the spec is an issue then it's probably a better solution to use a middleware that loads the files from some other medium (like disk, cdn, ...) and serves that as a static middleware and not embed the specs with `--exclude-spec`

File: generator/operation.go (hunk 1 above)
Comment (fredbi) [reply generator/operation.go]: Yes: that was the plan...

I would like that we update vendor beforehand. I can take care of that. Would you like to merge the pending PR in spec before that?
